### ISSUE TITLE
Relax agpl to gpl

### ISSUE THREAD

**Issue by davelab6** [theleagueof/fontship#35]
Anyone running Google corp hardware can't touch agpl code, so this can't be used in any GF projects until the license is relaxed to GPLv3

**Comment by alerque** [comment]
Hey @davelab6 thanks for the feedback. I'll be honest though, I'm not sure what to do with this yet.

First of all when I picked AGPL I did so very carefully with a certain case in mind I wanted to protect against. **That case was not Google Fonts**. That being said, I'm struggling to see how they would be different and whether we can reasonably guard against the one without hurting the other.

Fontship is designed very specifically to run both locally and remotely as a CI service. You ran run it as installed software (or a Docker image) on your local files, but it can also be run and accomplish the same things from a CI runner. The copy-left protection of the GPL is exactly what I wanted for the local side of things, but it leaves a loophole for hosted services. They could potentially extend the feature set of fix some bugs, run it on their servers, host it as a service, charge people for their improved version, and never contribute back because they don't distribute the software, only run a hosted version.

The one thing the Affero clauses do is extend the GPL to cover the case of network facing services running the software to require source availability. That doesn't seem too much to ask.

I don't want to discount or undermine the contributions Google Fonts has made to advance typography in general including subsidizing many font projects. At the end of the day if changing the license will benefit open source font projects then I'll probably be game for it. My goal was and is to give every advantage to those who contribute back in the spirit of open source — as long as I'm contributing a bunch of my time an effort into the void want it to be to the advantage of other open source projects as much as possible. Too often I've watched big industry players using their clout to keep small players out and marginalize open source projects. Given that this tool is specifically setup to run as a network facing service I wanted to avoid the situation where somebody offers it as a for-money product but doesn't while withholding their fixes and improvements from other players. How do we accomplish that?

CC: @chrissimpkins

**Comment by alerque** [comment]
Also what happens when we want to do something –as we've planned to do— like facilitate regenerating specimens after building the font? Almost any dependency we use for that will drag in AGPL code: LaTeX, Inkscape, Gimp, ImageMagic, and others all depend on Ghostscript which is AGPL. We'd run into it in many other tools we could reach for as well.

At this point Google doesn't host Git repositories or CI runners so I'm not sure what the deal would even be here. Even the main GF repo with a gagillian binary artifacts (uggg) is hosted no Github. What would be to stop some font project that's releasing their font under OFL terms anyway and is is already hosted on Github from enabling this in the CI to generate and post font releases?

**Comment by coredump2020** [comment]
@davelab6 Could you please comment on what @alerque said and tell us how we can move forward? Thanks a lot!

**Comment by tukusejssirs** [comment]
> The one thing the Affero clauses do for us is extend the GPL to explicitly cover the case of network facing services running the software to require source availability. That doesn't seem like an unreasonable thing to ask.

I am not a lawyer nor did I had to deal with the licensing for this kind of project, but how about using both licences? In the licence file, you would specify under what conditions one can use the code under which licence. There you would mention the network-facing services that they are required to use the AGPL licence.

**Comment by alerque** [comment]
> but how about using both licences?

From my perspective that would defeat the purpose of using the AGPL in the first place. I'm not a lawyer either but I think it would be difficult to near impossible to do a broad release under a dual license situation and target specific licenses to specific use cases. I know projects have attempted that but off hand my impression in that this has questionable legal standing. Usually in a dual license situation the consumer can choose which license terms they want to operate under. Dictating who uses which license when is much more complicated.

> There you would mention the network-facing services that they are required to use the AGPL licence.

Essentially the AGPL *is* what you describe anyway. It is the GPL with an extra clause mandating that network facing services also be bound by the terms of needing to release the source for any modifications / improvements they made. Otherwise the GPL has a loophole where you only have to publish the source if you publish a software package that includes modifications. It allows you to make modification and then host a service that uses them without allowing other projects to benefit.

What I don't want is for some big online font broker to take this, make a bunch of improvements to the build process, then offer it a service only to projects that host their fonts with them. Google Fonts is not the problem here since their build workflow is open anyway and the end product is font files that are freely distributed. What I have in mind is (without naming actual problematic sites) big_font_clearinghouse_x.com that could take my free-time OSS work, extend it some build improvements, then turn and around and offer it as a closed/for pay service to projects (perhaps only offering it to project that host with them) in such a way that you had to use their services to get the same font builds. I don't care if platforms host this as a service, but I do care that font project authors be able to build their own fonts projects and get the same result locally through another build provider of their choice.

I suppose one possible resolution might be to keep the project under AGPL by default but make sure myself and all other contributors authorize an exception case that explicitly licenses just Google for use in Google Fonts related builds to use it on any Google owned under GPL terms just to appease their crazy lawyers who make blanket rules like this and can't be bothered to look into specific use cases.

But getting anywhere on this issue requires hearing feedback from Google in the first place...

**Comment by davelab6** [comment]
> if changing the license will benefit open source font projects then I'll probably be game for it

I came back to this issue today because I have a Arabic typeface project that needs a Latin companion, and part of the weight range of Libertinus Sans would be a good candidate, but since it has a AGPL dependency, I believe I can't use it. 

So, changing the license will make liberating a specific OFL project. Please reconsider, and meanwhie I'm happy to continue the wider conversation:

> I wanted to avoid the situation where somebody offers it as a for-money product

I don't think that is a reasonable concern; there's no deep marketplace for such a product. 

Its like someone making font editor plugins; they might make $2,000 USD a year from retailing a proprietary plugin, but a developer can earn $2,000 USD in week at a $50/hour billable rate as a general contractor. So, a lot of people don't bother to use the retail distribution channels offered to them by editor vendors, and just throw everything on Github under a permissive license.

> I had in mind some other big industry foundries/players that have used their brute size to dominate the tooling market, used their domination to excuse bad tooling, and kept even the output made by the tooling behind exorbitant paywalls that fund corporations more than the creators. 

You'll have to be more specific and name names for my to comment further - I am struggling to guess what you are referring to. 

Domineering: No one dominates the tooling market, as I see it. 

Badness: AFDKO is old, but now libre. Fontlab 5 was bad for a long time, Fontlab 6 had a different set of badness, and Fontlab 7 is fine, I hear. RoboFont, Glyphs, FontCreator, FontForge - these are now also all fine, in so far as they are what they are, and addressing their shortcomings would mean changing their product values, so they won't do it. VOLT and VTT are almost abandoned and are so old they don't seem interesting even if they were liberated. 

Output behind Paywalls: Not sure what you refer to. Does MyFonts or Adobe Fonts have some QA tools that they offer their sellers? I'm ignorant of it.

There are A LOT of private tools that aren't available to the public, including font CI tools, but those aren't relevant to your argument, I think.

**Comment by davelab6** [comment]
@alerque a user requested adding https://github.com/alerque/libertinus to GF so I am looping back this :)

**Comment by alerque** [comment]
Yes I'll relax it to GPL. I've already gotten permission from all other contributors.

----

Google is a bully –sometimes an evil one– and I'm quite upset about it, but that isn't about this project (and nothing personal related to Dave).

**Comment by razvanm** [comment]
Is this still happening? I landed here trying to understand why Libertinus is not in Google Fonts. 😊
